/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/KakaoMapLike copy.vue')['default']
    DemoSwitchBasic: typeof import('./src/views/demos/DemoSwitchBasic.vue')['default']
    KakaoMap: typeof import('./src/components/KakaoMap.vue')['default']
    KakaoMapLike: typeof import('./src/components/KakaoMapLike.vue')['default']
    KakaoMapReco: typeof import('./src/components/testMap/KakaoMapReco.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
